### ISSUE TITLE
Fails to publish message to IoTHub

### ISSUE THREAD

**Issue by ndanzi** [Azure/azure-umqtt-c#10]
Hi all,

I'm trying to use this library to send messages to IoTHub broker, but it fails during the publish phase. In particular the `OnOperationComplete` callback is never called, so I am stuck in a infinite loop waiting for the `mqtt_client_dowork` to complete the publish operation. This is the code I'm using:

```
#include "azure_umqtt_c/mqtt_client.h"
#include "azure_c_shared_utility/socketio.h"
#include "azure_c_shared_utility/tls_config.h"
#include "azure_c_shared_utility/tlsio.h"
#include "azure_c_shared_utility/platform.h"
#include "azure_c_shared_utility/wsio.h"

std::string const MSG_BODY = "Message using umqtt: hello";

MQTT_CLIENT_HANDLE mqttHandle = NULL;
XIO_HANDLE xio = NULL;
bool isError = false;
bool connected = false;
bool published = false;
bool subscribed = false;
int packetId = 0;

void OnRecvCallback(MQTT_MESSAGE_HANDLE msgHandle, void* context)
{
    std::cout << "Recv callback" << std::endl;
}

void OnCloseComplete(void* context)
{
    std::cout << "close complete callback" << std::endl;
}

void OnOperationComplete(MQTT_CLIENT_HANDLE handle, MQTT_CLIENT_EVENT_RESULT actionResult, const void* msgInfo, void* callbackCtx)
{
    switch (actionResult)
    {
    case MQTT_CLIENT_ON_CONNACK:
    {
        std::cout << "connack called" << std::endl;
        connected = true;
        break;
    }
    case MQTT_CLIENT_ON_SUBSCRIBE_ACK:
    {
        std::cout << "subscribed_ack called" << std::endl;
        subscribed = true;
        break;
    }
    case MQTT_CLIENT_ON_PUBLISH_ACK:
    {
        std::cout << "publish_ack called" << std::endl;
        published = true;
        break;
    }
    case MQTT_CLIENT_ON_PUBLISH_RECV:
    {
        std::cout << "publish_recv called" << std::endl;
        break;
    }
    case MQTT_CLIENT_ON_PUBLISH_REL:
    {
        std::cout << "publish_rel called" << std::endl;
        break;
    }
    case MQTT_CLIENT_ON_PUBLISH_COMP:
    {
        std::cout << "publish_comp called" << std::endl;
        published = true;
        break;
    }
    case MQTT_CLIENT_ON_DISCONNECT:
        std::cout << "client disconnect called" << std::endl;
        connected = false;
        break;
    }
}

void OnErrorComplete(MQTT_CLIENT_HANDLE handle, MQTT_CLIENT_EVENT_ERROR error, void* callbackCtx)
{
    switch (error)
    {
    case MQTT_CLIENT_CONNECTION_ERROR:
        std::cout << "connection error" << std::endl;
        isError = true;
        connected = false;
        break;
    case MQTT_CLIENT_PARSE_ERROR:
        std::cout << "parse error" << std::endl;
        isError = true;
        connected = false;
        break;
    case MQTT_CLIENT_MEMORY_ERROR:
        std::cout << "memory error" << std::endl;
        isError = true;
        break;
    case MQTT_CLIENT_COMMUNICATION_ERROR:
        std::cout << "communication error" << std::endl;
        isError = true;
        connected = false;
        break;
    case MQTT_CLIENT_NO_PING_RESPONSE:
        std::cout <<"no ping response error" << std::endl;
        isError = true;
        connected = false;
        break;
    case MQTT_CLIENT_UNKNOWN_ERROR:
        std::cout << "unknown error" << std::endl;
        isError = true;
        connected = false;
        break;
    default:
        isError = true;
        connected = false;
        break;
    }
}

bool PublishMessage()
{
    published = false;

    std::stringstream msgText;
    msgText << MSG_BODY  << " # " << packetId;
    std::string msgTextString = msgText.str();
    std::cout << "trying to publish msg: \"" << msgTextString << "\"" << std::endl;
    std::vector<uint8_t> msgBody(msgTextString.begin(), msgTextString.end());
    MQTT_MESSAGE_HANDLE msg = mqttmessage_create(packetId++, TOPIC.c_str(), DELIVER_AT_LEAST_ONCE, &msgBody[0], msgBody.size());
    if (msg == NULL)
    {
        std::cout << "mqttmessage_create failed" << std::endl;
        return false;
    }

    if (mqtt_client_publish(mqttHandle, msg))
    {
        std::cout << "mqtt_client_publish failed" << std::endl;
        return false;
    }

    mqttmessage_destroy(msg);

    do
    {
        if (isError || !connected)
            return false;

        mqtt_client_dowork(mqttHandle);
    } while (!published);

    return true;
}

bool Connect()
{
    MQTT_CLIENT_OPTIONS options = { 0 };
    options.clientId = &CLIENTID[0];
    options.willMessage = NULL;
    options.username = &USERNAME[0];
    options.password = &PASSWORD[0];
    options.keepAliveInterval = 240;
    options.useCleanSession = false;
    options.qualityOfServiceValue = DELIVER_AT_LEAST_ONCE;
    if (mqtt_client_connect(mqttHandle, xio, &options) != 0)
    {
        std::cout << "mqtt_client_connect failed" << std::endl;
        return false;
    }

    do
    {
        if (isError)
            return false;

        mqtt_client_dowork(mqttHandle);
    } while (!connected);

    return true;
}

void Disconnect()
{
    xio_close(xio, OnCloseComplete, NULL);

    mqtt_client_deinit(mqttHandle);

    platform_deinit();
}

bool InitializeClient()
{
    if (platform_init() != 0)
    {
        std::cout << "platform_init failed" << std::endl;
        return false;
    }

    mqttHandle = mqtt_client_init(OnRecvCallback, OnOperationComplete, NULL, OnErrorComplete, NULL);
    if (mqttHandle == NULL)
    {
        std::cout << "mqtt_client_init failed" << std::endl;
        return false;
    }

    TLSIO_CONFIG tlsIOConfig;
    tlsIOConfig.hostname = HOST.c_str();
    tlsIOConfig.port = PORT;
    tlsIOConfig.underlying_io_interface = NULL;
    tlsIOConfig.underlying_io_parameters = NULL;

    const IO_INTERFACE_DESCRIPTION* tlsio_interface = platform_get_default_tlsio();
    xio = xio_create(tlsio_interface, &tlsIOConfig);


    if (xio == NULL)
    {
        std::cout << "xio_create failed" << std::endl;
        return false;
    }

    return true;
}

int main()
{
    if (!InitializeClient())
        return -1;

    if (!Connect())
        return -1;

    for (int i = 0; i < 10; i++)
    {
        if (!PublishMessage())
            break;
    }

    Disconnect();

    return 0;
}
```
The password is a SAS token generated by the Device Explorer tool.
I'm running library cloned from the master branch on commit 5bddc79. The example runs on Windows 10 and uses schannel.

**Comment by jebrando** [comment]
Can you enable logging in your app (mqtt_client_set_trace(mqttHandle, true, true)) and send me the resulting console log.

**Comment by ndanzi** [comment]
This is the logging:

-> 08:34:17 CONNECT: 0x10 0xd5 0x01 0x00 0x04 0x4d 0x51 0x54 0x54 0x04 0xc0 0x00 0xf0 0x00 0x0b 0x75 0x61 0x6d 0x71 0x70 0x44 0x65 0x76 0x69 0x63 0x65 0x00 0x29 0x75 0x6e 0x69 0x71 0x6c 0x6f 0x75 0x64 0x64 0x65 0x76 0x2e 0x61 0x7a 0x75 0x72 0x65 0x2d 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2e 0x6e 0x65 0x74 0x2f 0x75 0x61 0x6d 0x71 0x70 0x44 0x65 0x76 0x69 0x63 0x65 0x00 0x91 0x53 0x68 0x61 0x72 0x65 0x64 0x41 0x63 0x63 0x65 0x73 0x73 0x53 0x69 0x67 0x6e 0x61 0x74 0x75 0x72 0x65 0x20 0x73 0x72 0x3d 0x75 0x6e 0x69 0x71 0x6c 0x6f 0x75 0x64 0x64 0x65 0x76 0x2e 0x61 0x7a 0x75 0x72 0x65 0x2d 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2e 0x6e 0x65 0x74 0x25 0x32 0x46 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x25 0x32 0x46 0x75 0x61 0x6d 0x71 0x70 0x44 0x65 0x76 0x69 0x63 0x65 0x26 0x73 0x69 0x67 0x3d 0x77 0x76 0x52 0x6d 0x5a 0x51 0x52 0x58 0x65 0x33 0x38 0x67 0x45 0x62 0x59 0x4c 0x37 0x71 0x74 0x67 0x33 0x71 0x52 0x38 0x63 0x5a 0x58 0x62 0x48 0x69 0x45 0x6d 0x6a 0x42 0x4e 0x25 0x32 0x42 0x38 0x6a 0x57 0x76 0x46 0x78 0x6f 0x25 0x33 0x44 0x26 0x73 0x65 0x3d 0x31 0x34 0x39 0x37 0x36 0x31 0x39 0x38 0x33 0x31
-> 08:34:17 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: xxxxxxxx.azure-devices.net/myDevice | PWD: XXXX | CLEAN: 0
<- 08:34:18 CONNACK: 0x20 0x02 0x01 0x00
<- 08:34:18 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
connack called
trying to publish msg: "Message using umqtt: hello # 0"
-> 08:34:18 PUBLISH: 0x32 0x7b 0x00 0x59 0x64 0x65 0x76 0x69 0x63 0x65 0x73 0x2f 0x75 0x61 0x6d 0x71 0x70 0x44 0x65 0x76 0x69 0x63 0x65 0x2f 0x6d 0x65 0x73 0x73 0x61 0x67 0x65 0x73 0x2f 0x65 0x76 0x65 0x6e 0x74 0x73 0x2f 0x74 0x65 0x6d 0x70 0x65 0x72 0x61 0x74 0x75 0x72 0x65 0x41 0x6c 0x65 0x72 0x74 0x3d 0x66 0x61 0x6c 0x73 0x65 0x26 0x25 0x32 0x34 0x2e 0x63 0x69 0x64 0x3d 0x43 0x4f 0x52 0x45 0x5f 0x49 0x44 0x26 0x25 0x32 0x34 0x2e 0x6d 0x69 0x64 0x3d 0x4d 0x53 0x47 0x5f 0x49 0x44 0x00 0x00 0x4d 0x65 0x73 0x73 0x61 0x67 0x65 0x20 0x75 0x73 0x69 0x6e 0x67 0x20 0x75 0x6d 0x71 0x74 0x74 0x3a 0x20 0x68 0x65 0x6c 0x6c 0x6f 0x20 0x23 0x20 0x30
-> 08:34:18 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/myDevice/messages/events/temperatureAlert=false&%24.cid=CORE_ID&%24.mid=MSG_ID | PACKET_ID: 0 | PAYLOAD_LEN: 30

**Comment by jebrando** [comment]
mqtt spec
[MQTT-2.3.1-1] SUBSCRIBE, UNSUBSCRIBE, and PUBLISH (in cases where QoS > 0) Control Packets MUST contain a non-zero 16-bit Packet Identifier.

So your packet id needs to be greater than zero.  uMqtt should fail the packet if the packet id is 0, so I'll add that in there before the next release..

Cheers.
Jelani
