### ISSUE TITLE
Error on xio_close

### ISSUE THREAD

**Issue by ndanzi** [Azure/azure-umqtt-c#13]
Hi all,

I'm using this library (version tagged as Release 2017-06-16) with openssl and when I call `xio_close` I get the following error:
```
Invalid tlsio_state. Expected state is TLSIO_STATE_NOT_OPEN or TLSIO_STATE_CLOSING.
```
Actually `tls_io_instance->tlsio_state` is set to `TLSIO_STATE_NOT_OPEN` in function `on_underlying_io_close_complete` (file tlsio_opnessl.c). Then in `tlsio_openssl_close` function, the check fails because it finds the state to be not open.

Additionally I believe that error message printed by the `tlsio_openssl_close` function is misleading.

Thank you
Nicolo'

**Comment by tameraw** [comment]
@ndanzi - Thanks for filing this. We'll investigate it.

**Comment by JetstreamRoySprowl** [comment]
@ndanzi -- I'm working on this one now.

**Comment by JetstreamRoySprowl** [comment]
@ndanzi - You're right, the error message is incorrect, and I will fix that. It would also be preferable if the tlsio treated the close operation as idempotent, and that change may or may not make it in at this time.

**Comment by JetstreamRoySprowl** [comment]
@ndanzi - I've checked in a new version that fixes the error message. It will now tell you if it's being closed when already closed, but that is an acceptable operation and won't show as an error.
