### ISSUE TITLE
mqtt client does not handle ping response in the right way

### ISSUE THREAD

**Issue by powerhu** [Azure/azure-umqtt-c#15]
I write an example to use mqtt client, set mqtt keep alive to 10 seconds, I want to check whether it can handle ping message correctly, when I shutdown my wireless connection for more than 30 seconds, but the client did not send MQTT_CLIENT_NO_PING_RESPONSE message to error callback function.

My proposes:
1. compare current time with ping response time instead of ping send time since we need to check server could send response in time, or else we assume the connection is lost.

**Comment by tameraw** [comment]
@powerhu - Thanks for filing this issue. We'll investigate it.

**Comment by jebrando** [comment]
What OS are you working on?

**Comment by powerhu** [comment]
linux.
below fix could work
<img width="576" alt="fix" src="https://user-images.githubusercontent.com/21335703/29856222-fad64116-8d83-11e7-976f-e48b1145a171.png">
