### ISSUE TITLE
Publisher and Subscriber in the same client

### ISSUE THREAD

**Issue by nitol-saha** [Azure/azure-umqtt-c#153]
I want to implement 2 clients with feature of publisher and subscriber in the same client. 

Client 1: Publisher will send data in every 1 second and subscriber will listen for any incoming message in another topic. 

Client 2: Subscriber will receive any data and as soon as it receives the data it will publish the data to another topic. 

Can you provide me with any examples? I am new to this library. Facing some difficulties.

**Comment by ericwol-msft** [comment]
This is not a full MQTT client. Please consider [Eclipse Mosquitto Client](https://mosquitto.org/) or [Eclipse Paho C MQTT Client ](https://github.com/eclipse/paho.mqtt.c)Library
