### ISSUE TITLE
compiliation problems when mqtt_client .h included by a cpp file

### ISSUE THREAD

**Issue by tarichuo** [Azure/azure-umqtt-c#21]
Hi all,

There is a cpp file in my project that includes <mqtt_client.h>. When I try to build my project, there are many compile errors like this:
`In file included from /usr/local/include/azure_c_shared_utility/crt_abstractions.h:13:0,
                 from /usr/local/include/azure_umqtt_c/mqttconst.h:16,
                 from /usr/local/include/azure_umqtt_c/mqtt_client.h:16,
                 from /home/hjy/ota/unittest/remote/remote_unittest.cc:10:
/usr/include/c++/4.8/cmath: In function ‘constexpr float std::abs(float)’:
/usr/include/c++/4.8/cmath:87:16: error: declaration of C function ‘constexpr float std::abs(float)’ conflicts with
   abs(float __x)
                ^
/usr/include/c++/4.8/cmath:81:3: error: previous declaration ‘constexpr double std::abs(double)’ here
   abs(double __x)
`
I suppose it's because some cpp headers are included after an `extern "C"` macro, for example
`<cstddef> included by <mqttconst.h> included by <mqtt_client.h> which defines extern "C"` 
 So I put all includes before __cplusplus macro in inc folder and it works. I wonder if it's a bug or my usage fault?

Thanks
Tracihuo

**Comment by jebrando** [comment]
The headers have been updated for this issue, let me know if the problem persists.

**Comment by xiaowangtongxue123** [comment]
please this issue solved?

**Comment by xiaowangtongxue123** [comment]
consult this question solved?
