### ISSUE TITLE
UMQTT or Azure IoT SDK C?

### ISSUE THREAD

**Issue by forthlightning** [Azure/azure-umqtt-c#6]
I'm trying to send mqtt messages to Azure IoT Hub using the ESP32, and I see some conflicting resources. First off I know that both of these resources are based on the esp8266, and esp32 support may be some way out, but I am looking ahead to future Azure compatibility.

This Azure mqtt client shows one way to do it: [https://github.com/Azure/azure-umqtt-c/blob/master/samples/mqtt_client_sample/mqtt_client_sample.c](url)

And this Azure IoT SDK example shows another way to do it: [https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_mqtt_esp8266/iothub_client_sample_mqtt_esp8266.c](url)

Not sure which one I should be using... Any advice? At first glance the umqtt sample looks cleaner, but I have not dug into it too deeply.

**Comment by jebrando** [comment]
There are slight differences between the mqtt_client_sample and the iothub_client_sample_mqtt_exp8266. 

The mqtt_client_sample is a generic MQTT client that can connect to any MQTT server.
The iothub_client_sample_mqtt_exp8266 sample is used only to connect to azure iothub and cannot connect to any generic MQTT server.

Let me know if you have any more questions.

**Comment by forthlightning** [comment]
Thanks for the quick reply! 

I'm currently using PubSubClient [https://github.com/knolleary/pubsubclient](url) to connect to a generic mqtt server. One of the issues I'm running into while using PubSubClient is that it does not ensure QOS 1, specifically for Cloud to Device messages, is it correct to assume that both of the above approaches will allow for QOS 1? 

I'm also developing on the new ESP32, are these two repos good places to check for any pending support for the new SOC?

**Comment by jebrando** [comment]
Yes, Iothub and MQTT client support QOS1.  Looking at the iothub-sdk-c will give you an idea of all the support we have.

cheers.
