### ISSUE TITLE
Connect to IoTHub

### ISSUE THREAD

**Issue by ndanzi** [Azure/azure-umqtt-c#8]
Hi all,

I am not able to publish a message to IoTHub, I get a `MQTT_CLIENT_ON_CONNACK` and then a 'MQTT_CLIENT_CONNECTION_ERROR'. Maybe this is due to some parameter put in a wrong way. With the same parameters I am able to publish a message with another mqtt c client (Paho).

Could you please provide and example of how to connect and publish a message to IoTHub?

Thanks
Nicolo`

**Comment by ewertons** [comment]
Hi Nicolo,
Which sample from the repo after you running?
________________________________

**Comment by ndanzi** [comment]
I am running this sample:
https://github.com/Azure/azure-umqtt-c/blob/master/samples/mqtt_client_sample/mqtt_client_sample.c

Another question: Is there any way to manage the trustStore certificate in order to validate SSL connection to the server?

**Comment by tameraw** [comment]
@ndanzi - Have you considered using our IoT Hub client SDK (which uses this very library)? Any reasons not to use that?

**Comment by ndanzi** [comment]
@tameraw - thank you for reply, but that SDK doesn't accomplish the requirements of my project, in fact I must support connections to several MQTT brokers, not only IoT Hub. 

With this library I am able to connect to all those brokers (apollo, mosquitto, ecc) and the only broker I cannot send messages to is IoT Hub. 
The umqtt client connects to the IoT Hub but when I try to send a message to the broker, I get the OnErrorComplete callback called. My credentials are right, because with them I can connect with Paho Mqtt c library. As password I use a SAS token generated by token service.
I am also able to send messages to IoT Hub using your uamqp library.

I suppose I should change the disposition of my authentication parameters, but I cannot find any example of connection to IoT Hub using umqtt.

**Comment by tameraw** [comment]
@ndanzi - Here is the detailed doc on MQTT support for IoTHub:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support

**Comment by juanmartin** [comment]
Hi, I'm in a similar path. I need to get messages from mosquitto broker and send them to IoT Hub through a downstream device, so I'm trying to merge the iotedge_downstream_device_sample with the mqtt_client_sample.
I'm trying to understand the functions involved for this process, but cannot find any information. Were you able to accomplish this task?
