### ISSUE TITLE
Relationship between this library and Azure Iot SDK MQTT code?

### ISSUE THREAD

**Issue by JackUkleja** [Azure/azure-umqtt-c#9]
Hi,

Just curious what the relationship is between this library and the [MQTT code](https://github.com/Azure/azure-iot-sdk-csharp/tree/a5108f60f343dee867a2243e5a59c4483f0c5a8b/device/Microsoft.Azure.Devices.Client/Transport/Mqtt) in Azure Iot SDK?

Is this library intended to be used in embedded device only? If so, which library provides the server-side code for the IoT hub?

I am looking to use an MQTT server in a .NET project (that doesn't have access to the cloud). I see Azure IoT SDK is already providing me code for the client, but what about the server? Is the code for the MQTT part of Azure IoT Hub publicly available?

Cheers,
Jack

**Comment by tameraw** [comment]
@JackUkleja -
This library can be used by various MQTT clients. We use it in our Azure IoT SDK for C. It can be ported and used on various platforms.
It is not a MQTT broker. It is just the client with limited features pertaining to the IoT Hub usage.
The MQTT part of Azure IoT Hub is not publicly available. For that, we recommend you look at MQTT broker library solutions for .Net such as M2MQTT and others.
